const Putin = [
    {
        head: "WHO IS VLADIMIR PUTIN?",
        desc: 'Vladimir Putin, in full Vladimir Vladimirovich Putin, (born October 7, 1952, Leningrad, Russia, U.S.S.R. [now St. Petersburg, Russia]), Russian intelligence officer and politician who served as president (1999–2008, 2012– ) of Russia and also was the country’s prime minister (1999, 2008–12).',
    },
    {
        head: "EARLY CAREER",
        desc: "Putin studied law at Leningrad State University, where his tutor was Anatoly Sobchak, later one of the leading reform politicians of the perestroika period. Putin served 15 years as a foreign intelligence officer for the KGB (Committee for State Security), including six years in Dresden, East Germany. In 1990 he retired from active KGB service with the rank of lieutenant colonel and returned to Russia to become prorector of Leningrad State University with responsibility for the institution’s external relations. Soon afterward Putin became an adviser to Sobchak, the first democratically elected mayor of St. Petersburg. He quickly won Sobchak’s confidence and became known for his ability to get things done; by 1994 he had risen to the post of first deputy mayor.\n\nIn 1996 Putin moved to Moscow, where he joined the presidential staff as deputy to Pavel Borodin, the Kremlin’s chief administrator. Putin grew close to fellow Leningrader Anatoly Chubais and moved up in administrative positions. In July 1998 Pres. Boris Yeltsin made Putin director of the Federal Security Service (FSB; the KGB’s domestic successor), and shortly thereafter he became secretary of the influential Security Council. Yeltsin, who was searching for an heir to assume his mantle, appointed Putin prime minister in 1999.Although he was virtually unknown, Putin’s public-approval ratings soared when he launched a well-organized military operation against secessionist rebels in Chechnya. Wearied by years of Yeltsin’s erratic behaviour, the Russian public appreciated Putin’s coolness and decisiveness under pressure. Putin’s support for a new electoral bloc, Unity, ensured its success in the December parliamentary elections."
    },
    {
        head: "FIRST AND SECOND TERMS AS PRESIDENT OF RUSSIA",
        desc: 'On December 31, 1999, Yeltsin unexpectedly announced his resignation and named Putin acting president. Promising to rebuild a weakened Russia, the austere and reserved Putin easily won the March 2000 elections with about 53 percent of the vote. As president, he sought to end corruption and create a strongly regulated market economy.\n\nPutin quickly reasserted control over Russia’s 89 regions and republics, dividing them into seven new federal districts, each headed by a representative appointed by the president. He also removed the right of regional governors to sit in the Federation Council, the upper house of the Russian parliament. Putin moved to reduce the power of Russia’s unpopular financiers and media tycoons—the so-called “oligarchs”—by closing several media outlets and launching criminal proceedings against numerous leading figures. He faced a difficult situation in Chechnya, particularly from rebels who staged terrorist attacks in Moscow and guerilla attacks on Russian troops from the region’s mountains; in 2002 Putin declared the military campaign over, but casualties remained high.\n\nPutin strongly objected to U.S. Pres. George W. Bush’s decision in 2001 to abandon the 1972 Anti-Ballistic Missile Treaty. In response to the September 11 attacks on the United States in 2001, he pledged Russia’s assistance and cooperation in the U.S.-led campaign against terrorists and their allies, offering the use of Russia’s airspace for humanitarian deliveries and help in search-and-rescue operations. Nevertheless, Putin joined German Chancellor Gerhard Schröder and French Pres. Jacques Chirac in 2002–03 to oppose U.S. and British plans to use force to oust Saddam Hussein’s government in Iraq.\n\nOverseeing an economy that enjoyed growth after a prolonged recession in the 1990s, Putin was easily reelected in March 2004. In parliamentary elections in December 2007, Putin’s party, United Russia, won an overwhelming majority of seats. Though the fairness of the elections was questioned by international observers and by the Communist Party of the Russian Federation, the results nonetheless affirmed Putin’s power. With a constitutional provision forcing Putin to step down in 2008, he chose Dmitry Medvedev as his successor.',
    },
    {
        head: "PUTIN AS PRIME MINISTER",
        desc: "Soon after Medvedev won the March 2008 presidential election by a landslide, Putin announced that he had accepted the position of chairman of the United Russia party. Confirming widespread expectations, Medvedev nominated Putin as the country’s prime minister within hours of taking office on May 7, 2008. Russia’s parliament confirmed the appointment the following day. Although Medvedev grew more assertive as his term progressed, Putin was still regarded as the main power within the Kremlin.\n\nWhile some speculated that Medvedev might run for a second term, he announced in September 2011 that he and Putin would—pending a United Russia victory at the polls—trade positions. Widespread irregularities in parliamentary elections in December 2011 triggered a wave of popular protest, and Putin faced a surprisingly strong opposition movement in the presidential race. On March 4, 2012, however, Putin was elected to a third term as Russia’s president. In advance of his inauguration, Putin resigned as United Russia chairman, handing control of the party to Medvedev. He was inaugurated as president on May 7, 2012, and one of his first acts upon assuming office was to nominate Medvedev to serve as prime minister.",
    },
]

export {
    Putin,
};
